Change apikey
talkable/android-sdk pull request #8
Opened 2021-02-15 19:13 UTC by kostilal

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-14122)](https://talkable.atlassian.net/browse/PR-14122)

2021-02-24 12:23 UTC, dgtv requested changes

2021-02-24 12:23 UTC, dgtv commented on sdk/src/main/java/com/talkable/sdk/Talkable.java
> +            throw new IllegalArgumentException("You should specify Api Key and Site Slug inside AndroidManifest file");
```suggestion
            throw new IllegalStateException("You should specify Api Key and Site Slug inside AndroidManifest file");
```

2021-02-24 12:23 UTC, dgtv commented on sdk/src/main/java/com/talkable/sdk/Talkable.java
> +            throw new IncorrectInstallationException("Api key or Site slug should not be blank or null");
```suggestion
            throw new IllegalArgumentException("Api key or Site slug should not be blank");
```

2021-02-24 12:23 UTC, dgtv commented on sdk/src/main/java/com/talkable/sdk/Talkable.java
> +    public static void updateCredentials(String newApiKey, String newSiteSlug) {
```suggestion
    public static void setCredentials(String newApiKey, String newSiteSlug) {
```

2021-02-24 12:23 UTC, dgtv commented on sdk/src/main/java/com/talkable/sdk/Talkable.java
> +        credentialsMap.remove(siteSlug);
It is redundant, please remove

2021-02-24 12:23 UTC, dgtv commented on sdk/src/main/java/com/talkable/sdk/Talkable.java
> +        credentialsMap.put(siteSlug, newApiKey);
```suggestion
        credentialsMap.put(newSiteSlug, newApiKey);
        siteSlug = newSiteSlug;
```

2025-02-03 11:09 UTC, necroua commented
closing due to inactivity, reopen if needed

2025-02-03 11:09 UTC, closed without merging