Change apikey site slug
talkable/android-sdk pull request #9
Opened 2021-03-22 17:58 UTC by kostilal

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-15560)](https://talkable.atlassian.net/browse/PR-15560)

2021-03-26 13:23 UTC, dgtv requested changes

2021-03-26 13:23 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        Talkable.setServer(DEFAULT_SERVER);
No need to do this as DEFAULT_SERVER will be gotten by default if none is set

2021-03-26 13:23 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
>          Talkable.setSiteSlug("android");
It should be gotten from the input

2021-03-26 13:23 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
>          Talkable.setSiteSlug("android");
It should be gotten from the input

2021-03-26 13:23 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        setApiKeyAndSiteSlugIfNeeded();
Why not just call `updateTalkableCredentials` here?

2021-03-26 13:23 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        if (server.length() > 0 && server != DEFAULT_SERVER) {
I think that there should be a check that input is not blank

2021-04-02 13:30 UTC, dgtv requested changes

2021-04-02 13:30 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        if (server == null && server.length() > 0) {
Logic in this `if` looks like a bug. Also lets have just one method `updateTalkableCredentials` with all logic

2021-04-05 14:56 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
>          Talkable.setSiteSlug("android");
@kostilal up

2021-04-05 14:56 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
>          Talkable.setSiteSlug("android");
@kostilal up

2021-04-05 14:58 UTC, dgtv requested changes

2021-04-05 14:58 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        if (siteSlug.length() > 0 && apiKey.length() > 0) {
Looks like you should also check that it is not null

2021-04-05 14:58 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        EditText serverText = findViewById(R.id.serverText);
Please group all inputs together

2021-04-07 14:28 UTC, dgtv requested changes

2021-04-07 14:28 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +    }
```suggestion
    private void updateTalkableCredentials() {
        String siteSlug = findViewById(R.id.siteSlugText).getText().toString();
        String apiKey = findViewById(R.id.apiKeyText).getText().toString();
        String server = findViewById(R.id.serverText).getText().toString();

        if (siteSlug.length() > 0 && apiKey.length() > 0) {
            Talkable.updateCredentials(apiKey, siteSlug);
        } else {
            // show Toast with error and don't execute request
        }

        if (server != null && server.length() > 0) {
            Talkable.setServer(server);
        }
    }
```

2021-04-07 14:28 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        if (siteSlug.length() > 0 && apiKey.length() > 0) {
@kostilal up

2021-04-07 14:28 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        return text.getText().toString();
Looks like `null` case is not handled

2021-04-07 17:11 UTC, dgtv approved these changes

2021-04-07 17:11 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +        if (server != null && server.length() > 0) {
```suggestion
        if (server.length() > 0) {
```

2021-04-07 17:14 UTC, dgtv commented on app/src/main/java/com/talkable/demo/MainActivity.java
> +    private String campaignTag() {
```suggestion
    private String getCampaignTag() {
```

2025-02-03 11:10 UTC, necroua commented
closing due to inactivity, reopen if needed

2025-02-03 11:10 UTC, closed without merging